version: '3.9'

services:

  maria:
    image: mariadb:latest
    restart: always
    container_name: mariadb
    ports:
      - 63306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    environment:
      - MYSQL_PASSWORD=root2
      - MYSQL_USER=root
      - MYSQL_DATABASE=car_db
      - MYSQL_ROOT_PASSWORD=mypass
      - TZ="Asia/Seoul"

  nginx:
    depends_on:
      - api
      - ui
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    build:
      dockerfile: Dockerfile
      context: "./api"
    depends_on:
      - mariadb
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      MYSQL_HOST_IP: mariadb

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./ui
    volumes:
      - /app/node_modules
      - ./ui:/app